### ISSUE TITLE
Useless Prompt

### ISSUE THREAD

**Issue by NehemiahAT** [DrBeta/Friendly-Greeting#10]
When I open the page, the prompt asking me for my name immediately comes up, even though I didn't click the button. 

If I put something in the prompt and click "OK," the page still says "Hello!"

**Comment by DrBeta** [comment]
Will do

**Comment by NehemiahAT** [comment]
It stopped doing that already and you didn't change anything.

This is strange.

**Comment by DrBeta** [comment]
Now it's doing it for me

**Comment by NehemiahAT** [comment]
It might be a bug in our browser.

Do you use Edge?

**Comment by DrBeta** [comment]
Safari, but I fixed it

**Comment by NehemiahAT** [comment]
Okay.
