### ISSUE TITLE
Button Isn't Working

### ISSUE THREAD

**Issue by NehemiahAT** [DrBeta/Friendly-Greeting#12]
One of our fixes must've done something. The button is not working now.

**Comment by DrBeta** [comment]
My code editor said expression expected on this:

`myName === )`

**Comment by NehemiahAT** [comment]
Maybe we could do `myName === null || myName === "")`.

**Comment by DrBeta** [comment]
Isn't that what we had before.

**Comment by NehemiahAT** [comment]
We had `myName === null` before, according to my memory. I'll check the blame.

**Comment by NehemiahAT** [comment]
https://github.com/DrBeta/Friendly-Greeting/commit/5a46f0c8e30f9554c4d974fcc424c1e09bba60c9#diff-e8a233058211c77f51de535cd8ebb8d6.

It says `myName === null`.

**Comment by DrBeta** [comment]
Can you please handle this

**Comment by NehemiahAT** [comment]
Let me see what is going on here.

**Comment by DrBeta** [comment]
It is not working for me

**Comment by DrBeta** [comment]
It works!
