### ISSUE TITLE
Are Things Working For You?

### ISSUE THREAD

**Issue by NehemiahAT** [DrBeta/Friendly-Greeting#18]
For me, things are still not working.

If I click on the button, nothing happens.

**Comment by DrBeta** [comment]
Nope

**Comment by DrBeta** [comment]
it is not

**Comment by DrBeta** [comment]
Are you editing directly from the browser?

**Comment by NehemiahAT** [comment]
Yes, I am.

Were things working for v1.01?

**Comment by DrBeta** [comment]
Try using a code editor like VS Code, it will catch your errors and has GitHub integration. That is what I do.

**Comment by NehemiahAT** [comment]
Good advice. Thank you.

I'll use my CodePen.
