### ISSUE TITLE
Releases, Commits, and Branches

### ISSUE THREAD

**Issue by NehemiahAT** [DrBeta/Friendly-Greeting#23]
We have been changing this on the master branch between releases, which I think is a bad idea. We could be partially finished doing something while somebody comes along and uses our repository. I don't think I need to explain why we don't want this. I think that for all repositories we should change things in a separate branch, then merge that branch and master when we think we have rid the changes of bugs and then make it a new release. If you create a new branch for this purpose, we should do all our edits on that branch. If someone makes a mistake and tries to make a pull to master, we can politely ask them to pull to the other branch. This other branch can be our petri dish, where we can test things freely.

Do you think that's a good idea?

**Comment by NehemiahAT** [comment]
Also, I'm working on some cookies to remember people's names. I'm just afraid to break any law on cookies, because laws are various across many different places. The EU is especially strict.

**Comment by DrBeta** [comment]
There are different ways to do data besides cookies

**Comment by DrBeta** [comment]
It will not let me do a fork

**Comment by NehemiahAT** [comment]
Not a fork, a branch.

**Comment by DrBeta** [comment]
Ok

**Comment by DrBeta** [comment]
Branch created, I have to go.

**Comment by NehemiahAT** [comment]
Ok. Thanks.
