### ISSUE TITLE
Mobile Friendly

### ISSUE THREAD

**Issue by DrBeta** [DrBeta/Friendly-Greeting#6]
Could we make it mobile friendly with bootstrap?

**Comment by NehemiahAT** [comment]
Good idea.

Which version? I'm familiar with Bootstrap 3, but it is not the newest.

**Comment by DrBeta** [comment]
I'm familiar with 3 too. By the way, I made an improvement to the way null is handled.

**Comment by NehemiahAT** [comment]
Oh, thank you. I saw that "freedom" had done it.

**Comment by DrBeta** [comment]
oops, my computer username.

**Comment by NehemiahAT** [comment]
Here's a bunch of CDN's for the legacy Bootstrap versions: https://www.bootstrapcdn.com/legacy/bootstrap/.

**Comment by DrBeta** [comment]
https://getbootstrap.com/docs/3.3/ it says somewhere what the cdn is

**Comment by NehemiahAT** [comment]
CSS: https://stackpath.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css.

JS: https://stackpath.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js.

**Comment by NehemiahAT** [comment]
I couldn't find it where you said, so I just got the same version's CDN from the place I showed.

**Comment by DrBeta** [comment]
I already did it

**Comment by NehemiahAT** [comment]
Okay.
