### ISSUE TITLE
Is It Complete?

### ISSUE THREAD

**Issue by NehemiahAT** [DrBeta/Friendly-Greeting#9]
I think we should make what we currently have version 1.0. All you need to do is go into releases, and make a new release entitled v1.0.

The languages thing is a bit complicated and I think we should save that for another version. Don't you think?

**Comment by DrBeta** [comment]
I think so too. Version 1.0

**Comment by NehemiahAT** [comment]
Actually, no.

I just discovered a bug: when I first open the page, it shows the prompt. Even if I put something in the prompt and click "OK," the site still says "Hello!"

**Comment by DrBeta** [comment]
1.0.1 Will be our next release with this bug fix

**Comment by NehemiahAT** [comment]
Okay.

I'll make this a full issue so that people can easily see it.
